# workflow for log pull request between two tags
name: Python log

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./python

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: log out diff between tags
        run: |
          git log --pretty=oneline py/v0.3.5...py/v0.3.4 > log.txt
          cat log.txt
          echo "test"
#          echo "::set-output name=log_file::$(pwd)/log.txt"
#        id: log
#        shell: bash
#      - name: show log
#        run: |
#          cat ${{ steps.log.outputs.log_file }}