# workflow for log pull request between two tags
name: Python log

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./python

permissions:
  pull-requests: write

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: log out diff between tags
        run: |
          git log --oneline --grep=#\[0-9\] py/v0.3.4...py/v0.3.5 > diff.txt
          cat diff.txt
          echo "test"
      - name: curl label
        id: label
        env:
          GITHUB_TOKEN: ${{ secrets.QF_GITHUB_TOKEN }}
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/baidubce/bce-qianfan-sdk/pulls > pr.json
          echo "::set-output name=log_file::$(pwd)/pr.json"
      - name: show log
        run: |
          echo $(cat ${{ steps.label.outputs.log_file }})
          echo ${{ fromJson($(cat ${{ steps.label.outputs.log_file }})) }}
#          echo "${{ fromJson(steps.label.outputs.log_file) }}"
#          echo "${{ fromJson(steps.label.outputs.log_file)[0].labels[0].name }}"
# 打印json格式的log_file的labels属性
#          echo "::set-output name=log_file::$(pwd)/log.txt"
#        id: log
#        shell: bash
#      - name: show log
#        run: |
#          cat ${{ steps.log.outputs.log_file }}