name: Notebook CI

on:
#  push:   # 只有push触发
#    paths:
#      - 'cookbook/**/*.ipynb'  # cookbook目录下所有ipynb文件有改动时触发
#      - '!cookbook/.ipynb_checkpoints/**'  # 排除.ipynb_checkpoints目录下所有文件
  workflow_dispatch:  # 手动触发

defaults:
  run:
    shell: bash  # 默认shell为bash
    working-directory: ./cookbook  # 默认工作目录为cookbook

env:
  RUFF_OUTPUT_FORMAT: github


jobs:
  test:
    name: Notebook Unit Tests
    runs-on: ${{ matrix.os }}
    environment:
      name: my_bce_iam
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
#          - 'macos-latest'
#          - 'windows-latest'
        python-version:
#          - '3.7'
#          - '3.8'
          - '3.9'
#          - '3.10'
#          - '3.11'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  #     运行ipynb
      - name: pip_install
        uses: ./.github/workflows/pip_install.yml
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          ntbk_path: 'cookbook/RAG'
      - name: run_cookbook
        env:  # 配置环境变量
          QIANFAN_ACCESS_KEY: ${{ secrets.QIANFAN_ACCESS_KEY }}
          QIANFAN_SECRET_KEY: ${{ secrets.QIANFAN_SECRET_KEY }}
          KEYWORDS_DICT: ${{ secrets.KEYWORDS_DICT }}
          github_root: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}/python/test_CI && pytest -v -r A --full-trace  ${{ github.workspace }}/python/test_CI/test_ntbk::test_demo --ak "$QIANFAN_ACCESS_KEY" --sk "$QIANFAN_SECRET_KEY" --keywords "$KEYWORDS_DICT" --root-dir "$github_root"
